---
title: "stl_lead_inequity"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(janitor)
library(dplyr)
library(here)
```

```{r}
stl_lead <- read_csv(here::here("data/stl_lead.csv")) |>
  clean_names()
```

```{r}
stl_lead_prop <- mutate(stl_lead, prop_white = ((white / total_pop)*100))
```

```{r}
stl_lead_plot <- ggplot(stl_lead_prop, aes(x = prop_white, y = pct_elevated)) +
  geom_point(color = "cornflowerblue") +
  theme_light() +
  labs(title = "Percent elevated blood levels vs percent white", x = "Percent Elevated", y = "Percent White")
```

```{r}
ggsave(here("figs", "stl_lead_plot.png"), height = 6, width = 5)
```

The amount of lead in blood is negatively correlated with the proportion of white people.

```{r, fig.width=8,fig.height=6}
ggplot(stl_lead_prop, aes(x = pct_elevated)) +
  geom_histogram(fill = "pink2", color = "darkgreen") +
  labs(title = "Histogram of percent blood lead levels", x = "Percent blood lead levels", y= "Count")

ggsave(here("figs", "stl_lead_hist.jpg"), height = 6, width = 7)
```
